### ISSUE TITLE
website link in Newcastle pilot broken

### ISSUE THREAD

**Issue by ColmMassey** [p6data-coop/ise-linked-open-data#93] opened 2018-09-20 10:28 UTC
Follow
https://internal.solidarityeconomy.coop/maps/newcastle-pilot/
Search for blaydon
Select The Blaydon Shed
Click on The Blaydon shed icon and then click the website url.
It generates a 404
as has jumped to 
https://internal.solidarityeconomy.coop/maps/newcastle-pilot/www.blaydonshedswapstation.wordpress.com

where www.blaydonshedswapstation.wordpress.com
is a functioning website.

**Comment by matt-wallis** [comment] 2018-09-20 10:45
The cause of this is 'bad' input data: There's no http:// prefix on the website in the CSV.

My view is that the correct fix is to change the input data. The alternative leads us into a path of cunning heuristics to fix incorrect URLs. Do you agree @ColmMassey ?

**Comment by ColmMassey** [comment] 2018-09-20 11:10
Most people expect browsers to auto interpret www.whatever.com correctly. I'm not sure what they do. Probably look for https://www.whatever.com and if that fails look for http://www.whatever.com
Is there a standard way of interpreting them?

**Comment by matt-wallis** [comment] 2018-09-20 11:49
> Most people expect browsers to auto interpret [www.whatever.com](http://www.whatever.com) correctly.

So you think we need to handle this kind of input? 99% of the websites in the Newbridge CSV do not have this problem. 

> Is there a standard way of interpreting them?

i don't know. As you say, I expect that modern browsers take a trial and error approach along the lines you suggest. I wouldn't want to implement that in our javascript: much better to get the correct data in the LOD. That way it's usable by anyone who reads the LOD

**Comment by ColmMassey** [comment] 2018-09-20 12:02
Ok, so can we identify it's invalid on import and gernerate an error message as you did for the other fialed records.

**Comment by matt-wallis** [comment] 2018-09-20 13:00
The reason we're seeing this example on the newbridge map is that the newbridge data was not deleted from the triple store before its most recent update. So, an old triple (with the homepage) remains in the triplestore.
The error checking and reporting *is* already being done for newbridge - the report.csv sent to them already contains the message 
```
This doesn't look like a website: www.blaydonshedswapstation.wordpress.com (Maybe it's missing the http:// ?)
```

So the fix for this bug is to delate the old triples before we next update the triplestore.

**Comment by matt-wallis** [comment] 2018-11-20 14:41
@ColmMassey - anything left to do? If not, please close. Ta

**Closed as completed** 2018-11-20 15:18 UTC
Labels: bug
