### ISSUE TITLE
Add close buttons to panels on mobile

### ISSUE THREAD

**Issue by joebillings** [p6data-coop/ise-linked-open-data#162] opened 2019-09-02 07:31 UTC
And make the tab close the entire panel. We should also see what this is like in desktop mode for consistency.

**Comment by ColmMassey** [comment] 2019-09-05 10:32
Is this a duplicate of 
https://github.com/SolidarityEconomyAssociation/open-data-and-maps-outreach/issues/177 or are there some differences.

**Comment by joebillings** [comment] 2019-09-05 10:34
Yes, it looks like it. Can we close 177 and use this instead as it's not part of outreach?

**Closed as completed** 2019-09-12 12:10 UTC
